def user_exception_handler(exc, context):
    pass
